name: Publish

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: unit_agent
            asset_name: unit_agent-linux-amd64
          - os: windows-latest
            artifact_name: unit_agent.exe
            asset_name: unit_agent-windows-amd64
          - os: macos-latest
            artifact_name: unit_agent
            asset_name: unit_agent-macos-amd64

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --all-features

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
